#!/bin/bash
#
# Auto-generated markdown cleanup script
# Generated: Tue Jan 27 11:31:46 EST 2026
#

set -euo pipefail

echo 'Cleaning up unauthorized markdown files...'

echo 'Removing ./Docs/ACCESSIBILITY_TESTING_SUMMARY.md'
rm -f "./Docs/ACCESSIBILITY_TESTING_SUMMARY.md"
echo 'Removing ./Docs/APP_RENAME_SUMMARY.md'
rm -f "./Docs/APP_RENAME_SUMMARY.md"
echo 'Removing ./Docs/ASSIGNMENTS_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/ASSIGNMENTS_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/BUILD_FIX_COMPLETE.md'
rm -f "./Docs/BUILD_FIX_COMPLETE.md"
echo 'Removing ./Docs/BUILD_STATUS_SUMMARY.md'
rm -f "./Docs/BUILD_STATUS_SUMMARY.md"
echo 'Removing ./Docs/BUILD_SUCCESS_FINAL.md'
rm -f "./Docs/BUILD_SUCCESS_FINAL.md"
echo 'Removing ./Docs/BUILD_SUCCESS_SUMMARY.md'
rm -f "./Docs/BUILD_SUCCESS_SUMMARY.md"
echo 'Removing ./Docs/CENTERING_IMPLEMENTATION_COMPLETE.md'
rm -f "./Docs/CENTERING_IMPLEMENTATION_COMPLETE.md"
echo 'Removing ./Docs/CHINESE_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/CHINESE_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_FINAL_SUMMARY.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_FINAL_SUMMARY.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_SYNC_COMPLETE.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_SYNC_COMPLETE.md"
echo 'Removing ./Docs/COURSES_EXCELLENT_STATUS.md'
rm -f "./Docs/COURSES_EXCELLENT_STATUS.md"
echo 'Removing ./Docs/DANISH_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/DANISH_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/DASHBOARD_EXCELLENT_STATUS.md'
rm -f "./Docs/DASHBOARD_EXCELLENT_STATUS.md"
echo 'Removing ./Docs/DOCUMENTATION_UPDATE_SUMMARY.md'
rm -f "./Docs/DOCUMENTATION_UPDATE_SUMMARY.md"
echo 'Removing ./Docs/DUTCH_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/DUTCH_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/EVENT_DELETION_CONFIRMATION_COMPLETE.md'
rm -f "./Docs/EVENT_DELETION_CONFIRMATION_COMPLETE.md"
echo 'Removing ./Docs/EVENT_DELETION_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/EVENT_DELETION_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/FARSI_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/FARSI_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/FILE_CLASSIFICATION_PHASE2_COMPLETE.md'
rm -f "./Docs/FILE_CLASSIFICATION_PHASE2_COMPLETE.md"
echo 'Removing ./Docs/FILE_CLASSIFICATION_PHASE2_SUMMARY.md'
rm -f "./Docs/FILE_CLASSIFICATION_PHASE2_SUMMARY.md"
echo 'Removing ./Docs/FINAL_DIAGNOSIS_OLD.md'
rm -f "./Docs/FINAL_DIAGNOSIS_OLD.md"
echo 'Removing ./Docs/FINNISH_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/FINNISH_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/FRENCH_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/FRENCH_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/AI_ENGINE_SAFETY_CRITICAL_COMPLETE.md'
rm -f "./Docs/History/Completions/AI_ENGINE_SAFETY_CRITICAL_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/AI_PORTS_ARCHITECTURE_COMPLETE.md'
rm -f "./Docs/History/Completions/AI_PORTS_ARCHITECTURE_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/ALGORITHM_TEST_SUITE_SUMMARY.md'
rm -f "./Docs/History/Completions/ALGORITHM_TEST_SUITE_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/APP_WARNINGS_SUMMARY.md'
rm -f "./Docs/History/Completions/APP_WARNINGS_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/BUILD_CHECK_COMPLETE.md'
rm -f "./Docs/History/Completions/BUILD_CHECK_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/BUILD_FIX_SUMMARY.md'
rm -f "./Docs/History/Completions/BUILD_FIX_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/BUILD_TEST_SUMMARY.md'
rm -f "./Docs/History/Completions/BUILD_TEST_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/BULK_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/History/Completions/BULK_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/CALENDAR_PICKER_REMOVAL_COMPLETE.md'
rm -f "./Docs/History/Completions/CALENDAR_PICKER_REMOVAL_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/CALENDAR_PICKER_REMOVAL_SUMMARY.md'
rm -f "./Docs/History/Completions/CALENDAR_PICKER_REMOVAL_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/DASHBOARD_COMPLETE_ALL_ITERATIONS.md'
rm -f "./Docs/History/Completions/DASHBOARD_COMPLETE_ALL_ITERATIONS.md"
echo 'Removing ./Docs/History/Completions/DASHBOARD_HIG_IMPLEMENTATION_COMPLETE.md'
rm -f "./Docs/History/Completions/DASHBOARD_HIG_IMPLEMENTATION_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/DASHBOARD_ITERATIONS_2-5_COMPLETE.md'
rm -f "./Docs/History/Completions/DASHBOARD_ITERATIONS_2-5_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/DOCUMENTATION_PROFESSIONALIZATION_SUMMARY.md'
rm -f "./Docs/History/Completions/DOCUMENTATION_PROFESSIONALIZATION_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/ERROR_FIXES_COMPLETE.md'
rm -f "./Docs/History/Completions/ERROR_FIXES_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/ERROR_FIXES_SUMMARY.md'
rm -f "./Docs/History/Completions/ERROR_FIXES_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/FLASHCARD_SYSTEM_COMPLETE.md'
rm -f "./Docs/History/Completions/FLASHCARD_SYSTEM_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/I18N_ISSUES_83_84_85_COMPLETE.md'
rm -f "./Docs/History/Completions/I18N_ISSUES_83_84_85_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/I18N_SESSION_SUMMARY_DEC22.md'
rm -f "./Docs/History/Completions/I18N_SESSION_SUMMARY_DEC22.md"
echo 'Removing ./Docs/History/Completions/IMPLEMENTATION_COMPLETE.md'
rm -f "./Docs/History/Completions/IMPLEMENTATION_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/INTERFACE_SETTINGS_COMPLETE.md'
rm -f "./Docs/History/Completions/INTERFACE_SETTINGS_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/IOS_NATIVE_MENUS_COMPLETE.md'
rm -f "./Docs/History/Completions/IOS_NATIVE_MENUS_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/IOS_NAVIGATION_REFACTOR_SUMMARY.md'
rm -f "./Docs/History/Completions/IOS_NAVIGATION_REFACTOR_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/IOS_TAB_BAR_CUSTOMIZATION_COMPLETE.md'
rm -f "./Docs/History/Completions/IOS_TAB_BAR_CUSTOMIZATION_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/KEYBOARD_NAV_SUMMARY.md'
rm -f "./Docs/History/Completions/KEYBOARD_NAV_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/LAYOUT_FIXES_SUMMARY.md'
rm -f "./Docs/History/Completions/LAYOUT_FIXES_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/LLM_CALL_COUNTER_COMPLETE.md'
rm -f "./Docs/History/Completions/LLM_CALL_COUNTER_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/LLM_ENFORCEMENT_LOCK_IN_COMPLETE.md'
rm -f "./Docs/History/Completions/LLM_ENFORCEMENT_LOCK_IN_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/LOCALIZATION_AUDIT_SUMMARY.md'
rm -f "./Docs/History/Completions/LOCALIZATION_AUDIT_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/LOCALIZATION_EXPORT_SUMMARY.md'
rm -f "./Docs/History/Completions/LOCALIZATION_EXPORT_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/LOCALIZATION_FIX_SUMMARY.md'
rm -f "./Docs/History/Completions/LOCALIZATION_FIX_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/MACOS_ACCENT_COLOR_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/History/Completions/MACOS_ACCENT_COLOR_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/MACOS_BUILD_FIX_COMPLETE.md'
rm -f "./Docs/History/Completions/MACOS_BUILD_FIX_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/NOTIFICATIONS_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/History/Completions/NOTIFICATIONS_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/PRACTICE_TESTING_COMPLETE.md'
rm -f "./Docs/History/Completions/PRACTICE_TESTING_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/RELEASE_SAFE_CLEANUP_COMPLETE.md'
rm -f "./Docs/History/Completions/RELEASE_SAFE_CLEANUP_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/REPOSITORY_LOCKDOWN_SUMMARY.md'
rm -f "./Docs/History/Completions/REPOSITORY_LOCKDOWN_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/RUNTIME_ERRORS_FIX_SUMMARY.md'
rm -f "./Docs/History/Completions/RUNTIME_ERRORS_FIX_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/SESSION_COMPLETION_REPORT.md'
rm -f "./Docs/History/Completions/SESSION_COMPLETION_REPORT.md"
echo 'Removing ./Docs/History/Completions/SESSION_SUMMARY_DEC22.md'
rm -f "./Docs/History/Completions/SESSION_SUMMARY_DEC22.md"
echo 'Removing ./Docs/History/Completions/SESSION_SUMMARY_DEC29_EVENING.md'
rm -f "./Docs/History/Completions/SESSION_SUMMARY_DEC29_EVENING.md"
echo 'Removing ./Docs/History/Completions/SETTINGS_FIX_AND_FEEDBACK_SUMMARY.md'
rm -f "./Docs/History/Completions/SETTINGS_FIX_AND_FEEDBACK_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/SETTINGS_TAB_REMOVAL_COMPLETE.md'
rm -f "./Docs/History/Completions/SETTINGS_TAB_REMOVAL_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/SMART_ICLOUD_SYNC_COMPLETE.md'
rm -f "./Docs/History/Completions/SMART_ICLOUD_SYNC_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/TIMER_AUDIO_FEEDBACK_COMPLETE_OLD.md'
rm -f "./Docs/History/Completions/TIMER_AUDIO_FEEDBACK_COMPLETE_OLD.md"
echo 'Removing ./Docs/History/Completions/TIMER_BACKEND_REFACTOR_SUMMARY.md'
rm -f "./Docs/History/Completions/TIMER_BACKEND_REFACTOR_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/TIMER_PAGE_REFACTOR_SUMMARY.md'
rm -f "./Docs/History/Completions/TIMER_PAGE_REFACTOR_SUMMARY.md"
echo 'Removing ./Docs/History/Completions/UI_LOCALIZATION_AUDIT_COMPLETE.md'
rm -f "./Docs/History/Completions/UI_LOCALIZATION_AUDIT_COMPLETE.md"
echo 'Removing ./Docs/History/Completions/WATCHOS_BUILD_FIX_COMPLETE.md'
rm -f "./Docs/History/Completions/WATCHOS_BUILD_FIX_COMPLETE.md"
echo 'Removing ./Docs/History/Issues/ISSUE_175H_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_175H_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_182_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_182_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_182_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_182_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_208_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_208_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_332_STATUS.md'
rm -f "./Docs/History/Issues/ISSUE_332_STATUS.md"
echo 'Removing ./Docs/History/Issues/ISSUE_333_STATUS.md'
rm -f "./Docs/History/Issues/ISSUE_333_STATUS.md"
echo 'Removing ./Docs/History/Issues/ISSUE_342_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_342_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_343_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_343_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_345_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_345_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_349_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_349_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_350_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_350_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_351_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_351_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_351_VISUAL_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_351_VISUAL_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_383_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_383_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_386_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_386_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_388_INTEGRATION_COMPLETE.md'
rm -f "./Docs/History/Issues/ISSUE_388_INTEGRATION_COMPLETE.md"
echo 'Removing ./Docs/History/Issues/ISSUE_477_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_477_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_478_COMPLETION_SUMMARY.md'
rm -f "./Docs/History/Issues/ISSUE_478_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/History/Issues/ISSUE_86_SIMPLIFIED_CHINESE_COMPLETE.md'
rm -f "./Docs/History/Issues/ISSUE_86_SIMPLIFIED_CHINESE_COMPLETE.md"
echo 'Removing ./Docs/History/Issues/ISSUE_88_CHINESE_KEYWORDS_COMPLETE.md'
rm -f "./Docs/History/Issues/ISSUE_88_CHINESE_KEYWORDS_COMPLETE.md"
echo 'Removing ./Docs/History/Status/BUILD_FIX_STATUS_DEC29.md'
rm -f "./Docs/History/Status/BUILD_FIX_STATUS_DEC29.md"
echo 'Removing ./Docs/History/Status/BUILD_FIX_STATUS_OLD.md'
rm -f "./Docs/History/Status/BUILD_FIX_STATUS_OLD.md"
echo 'Removing ./Docs/History/Status/BUILD_FIX_STATUS.md'
rm -f "./Docs/History/Status/BUILD_FIX_STATUS.md"
echo 'Removing ./Docs/History/Status/BUILD_STATUS.md'
rm -f "./Docs/History/Status/BUILD_STATUS.md"
echo 'Removing ./Docs/History/Status/DEFAULT_DASHBOARD_LAUNCH_STATUS.md'
rm -f "./Docs/History/Status/DEFAULT_DASHBOARD_LAUNCH_STATUS.md"
echo 'Removing ./Docs/History/Status/ICLOUD_STATUS_TEXT_FIX.md'
rm -f "./Docs/History/Status/ICLOUD_STATUS_TEXT_FIX.md"
echo 'Removing ./Docs/HYBRID_AI_ARCHITECTURE_COMPLETE.md'
rm -f "./Docs/HYBRID_AI_ARCHITECTURE_COMPLETE.md"
echo 'Removing ./Docs/ICLOUD_FILE_MODULE_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/ICLOUD_FILE_MODULE_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/IMPLEMENTATION_PHASES_BCD.md'
rm -f "./Docs/IMPLEMENTATION_PHASES_BCD.md"
echo 'Removing ./Docs/IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/IOS_LOCALIZATION_PROGRESS.md'
rm -f "./Docs/IOS_LOCALIZATION_PROGRESS.md"
echo 'Removing ./Docs/ISSUE_396_PROGRESS.md'
rm -f "./Docs/ISSUE_396_PROGRESS.md"
echo 'Removing ./Docs/KEYBOARD_NAVIGATION_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/KEYBOARD_NAVIGATION_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/LOCALIZATION_FIX_COMPLETE.md'
rm -f "./Docs/LOCALIZATION_FIX_COMPLETE.md"
echo 'Removing ./Docs/LOCALIZATION_IMPLEMENTATION_SUMMARY.md'
rm -f "./Docs/LOCALIZATION_IMPLEMENTATION_SUMMARY.md"
echo 'Removing ./Docs/LOCALIZATION_PHASE2_SUMMARY.md'
rm -f "./Docs/LOCALIZATION_PHASE2_SUMMARY.md"
echo 'Removing ./Docs/Other/CRITICAL_TASKS_COMPLETION_SUMMARY.md'
rm -f "./Docs/Other/CRITICAL_TASKS_COMPLETION_SUMMARY.md"
echo 'Removing ./Docs/Other/PHASE_2_COMPLETE.md'
rm -f "./Docs/Other/PHASE_2_COMPLETE.md"
echo 'Removing ./Docs/Other/PROFESSIONAL_POLISH_SUMMARY.md'
rm -f "./Docs/Other/PROFESSIONAL_POLISH_SUMMARY.md"
echo 'Removing ./Docs/PHASE_2_5_PARTIAL.md'
rm -f "./Docs/PHASE_2_5_PARTIAL.md"
echo 'Removing ./Docs/PHASE_2_COMPLETE.md'
rm -f "./Docs/PHASE_2_COMPLETE.md"
echo 'Removing ./Docs/PHASE_3_AUDIT_RESULTS.md'
rm -f "./Docs/PHASE_3_AUDIT_RESULTS.md"
echo 'Removing ./Docs/PHASE_4_TASK_ALARMS_IMPLEMENTATION.md'
rm -f "./Docs/PHASE_4_TASK_ALARMS_IMPLEMENTATION.md"
echo 'Removing ./Docs/PHASE_4_TASK_ALARMS_QUICK_REFERENCE.md'
rm -f "./Docs/PHASE_4_TASK_ALARMS_QUICK_REFERENCE.md"
echo 'Removing ./Docs/PHASE1_IMPLEMENTATION_COMPLETE.md'
rm -f "./Docs/PHASE1_IMPLEMENTATION_COMPLETE.md"
echo 'Removing ./Docs/PHASE2_ALARMKIT_COMPLETE.md'
rm -f "./Docs/PHASE2_ALARMKIT_COMPLETE.md"
echo 'Removing ./Docs/PHASE2_BYO_IMPLEMENTATION_COMPLETE.md'
rm -f "./Docs/PHASE2_BYO_IMPLEMENTATION_COMPLETE.md"
echo 'Removing ./Docs/PHASE3_LIVE_ACTIVITY_COMPLETE.md'
rm -f "./Docs/PHASE3_LIVE_ACTIVITY_COMPLETE.md"
echo 'Removing ./Docs/PLANNER_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/PLANNER_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_COMPLETE.md'
rm -f "./Docs/PLATFORM_UNIFICATION_COMPLETE.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_SUMMARY.md'
rm -f "./Docs/PLATFORM_UNIFICATION_SUMMARY.md"
echo 'Removing ./Docs/PRACTICE_TESTING_V1_COMPLETE.md'
rm -f "./Docs/PRACTICE_TESTING_V1_COMPLETE.md"
echo 'Removing ./Docs/PRODUCTION_PREP_COMPLETE.md'
rm -f "./Docs/PRODUCTION_PREP_COMPLETE.md"
echo 'Removing ./Docs/PRODUCTION_PREP_STATUS_v1.0.md'
rm -f "./Docs/PRODUCTION_PREP_STATUS_v1.0.md"
echo 'Removing ./Docs/PRODUCTION_PREP_STATUS.md'
rm -f "./Docs/PRODUCTION_PREP_STATUS.md"
echo 'Removing ./Docs/RECURRENCE_FIX_COMPLETE.md'
rm -f "./Docs/RECURRENCE_FIX_COMPLETE.md"
echo 'Removing ./Docs/SUBSCRIPTION_INTEGRATION_STATUS.md'
rm -f "./Docs/SUBSCRIPTION_INTEGRATION_STATUS.md"
echo 'Removing ./Docs/SWAHILI_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/SWAHILI_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/TEST_COVERAGE_STATUS.md'
rm -f "./Docs/TEST_COVERAGE_STATUS.md"
echo 'Removing ./Docs/TEST_FAILURES_QUICK_SUMMARY.md'
rm -f "./Docs/TEST_FAILURES_QUICK_SUMMARY.md"
echo 'Removing ./Docs/TESTGEN_FIXTURE_CORPUS_SUMMARY.md'
rm -f "./Docs/TESTGEN_FIXTURE_CORPUS_SUMMARY.md"
echo 'Removing ./Docs/THAI_LOCALIZATION_COMPLETE.md'
rm -f "./Docs/THAI_LOCALIZATION_COMPLETE.md"
echo 'Removing ./Docs/TIMER_ENHANCEMENTS_SUMMARY.md'
rm -f "./Docs/TIMER_ENHANCEMENTS_SUMMARY.md"
echo 'Removing ./Docs/TIMER_PAGE_RESTORATION_PROGRESS.md'
rm -f "./Docs/TIMER_PAGE_RESTORATION_PROGRESS.md"
echo 'Removing ./Docs/V2_BRANCH_SUMMARY.md'
rm -f "./Docs/V2_BRANCH_SUMMARY.md"
echo 'Removing ./Docs/WATCHOS_BUILD_FIX_FINAL.md'
rm -f "./Docs/WATCHOS_BUILD_FIX_FINAL.md"
echo 'Removing ./Docs/WATCHOS_COMPANION_FINAL_REPORT.md'
rm -f "./Docs/WATCHOS_COMPANION_FINAL_REPORT.md"
echo 'Removing ./Docs/WEEK_1_SESSION_MIGRATION.md'
rm -f "./Docs/WEEK_1_SESSION_MIGRATION.md"
echo 'Removing ./Tests/COMPREHENSIVE_SESSION_STATUS.md'
rm -f "./Tests/COMPREHENSIVE_SESSION_STATUS.md"
echo 'Removing ./Tests/COMPREHENSIVE_STATUS.md'
rm -f "./Tests/COMPREHENSIVE_STATUS.md"
echo 'Removing ./Tests/FINAL_STATUS.md'
rm -f "./Tests/FINAL_STATUS.md"
echo 'Removing ./Tests/PHASE1_ACTION_REQUIRED.md'
rm -f "./Tests/PHASE1_ACTION_REQUIRED.md"
echo 'Removing ./Tests/PHASE2_COMPLETE.md'
rm -f "./Tests/PHASE2_COMPLETE.md"
echo 'Removing ./Tests/PHASE3_PROGRESS.md'
rm -f "./Tests/PHASE3_PROGRESS.md"
echo 'Removing ./Tests/SESSION_FINAL_STATUS.md'
rm -f "./Tests/SESSION_FINAL_STATUS.md"
echo 'Removing ./Tests/SESSION_SUMMARY.md'
rm -f "./Tests/SESSION_SUMMARY.md"
echo 'Removing ./Tests/TEST_INFRASTRUCTURE_SUMMARY.md'
rm -f "./Tests/TEST_INFRASTRUCTURE_SUMMARY.md"
echo 'Removing ./Docs/ACCESSIBILITY_TESTING_INDEX.md'
rm -f "./Docs/ACCESSIBILITY_TESTING_INDEX.md"
echo 'Removing ./Docs/APPICON_FIX.md'
rm -f "./Docs/APPICON_FIX.md"
echo 'Removing ./Docs/BINARY_CRASH_FIX.md'
rm -f "./Docs/BINARY_CRASH_FIX.md"
echo 'Removing ./Docs/BUILD_FIX_REPORT.md'
rm -f "./Docs/BUILD_FIX_REPORT.md"
echo 'Removing ./Docs/BUILD_FIX_REQUIRED.md'
rm -f "./Docs/BUILD_FIX_REQUIRED.md"
echo 'Removing ./Docs/BUILD_FIX_ROOTTAB_STRINGSDATA.md'
rm -f "./Docs/BUILD_FIX_ROOTTAB_STRINGSDATA.md"
echo 'Removing ./Docs/BUILD_FIXES_2026_01_03.md'
rm -f "./Docs/BUILD_FIXES_2026_01_03.md"
echo 'Removing ./Docs/BUILD_READINESS_REPORT.md'
rm -f "./Docs/BUILD_READINESS_REPORT.md"
echo 'Removing ./Docs/CALENDAR_DATE_HIGHLIGHT_FIX.md'
rm -f "./Docs/CALENDAR_DATE_HIGHLIGHT_FIX.md"
echo 'Removing ./Docs/CALENDAR_EVENT_OVERFLOW_FIX.md'
rm -f "./Docs/CALENDAR_EVENT_OVERFLOW_FIX.md"
echo 'Removing ./Docs/CALENDAR_LOCALIZATION_FIX.md'
rm -f "./Docs/CALENDAR_LOCALIZATION_FIX.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_INDEX.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_INDEX.md"
echo 'Removing ./Docs/CORE_DATA_REUSE_FIX.md'
rm -f "./Docs/CORE_DATA_REUSE_FIX.md"
echo 'Removing ./Docs/COURSES_LOCALIZATION_FIX.md'
rm -f "./Docs/COURSES_LOCALIZATION_FIX.md"
echo 'Removing ./Docs/DASHBOARD_HIG_ANALYSIS.md'
rm -f "./Docs/DASHBOARD_HIG_ANALYSIS.md"
echo 'Removing ./Docs/DASHBOARD_LOCALIZATION_FIX.md'
rm -f "./Docs/DASHBOARD_LOCALIZATION_FIX.md"
echo 'Removing ./Docs/DUPLICATE_WINDOW_FIX.md'
rm -f "./Docs/DUPLICATE_WINDOW_FIX.md"
echo 'Removing ./Docs/ERROR_STATE_AUDIT.md'
rm -f "./Docs/ERROR_STATE_AUDIT.md"
echo 'Removing ./Docs/EVENTKIT_PERMISSION_FIX.md'
rm -f "./Docs/EVENTKIT_PERMISSION_FIX.md"
echo 'Removing ./Docs/FATAL_ERROR_FIXED.md'
rm -f "./Docs/FATAL_ERROR_FIXED.md"
echo 'Removing ./Docs/HIG_COMPLIANCE_AUDIT.md'
rm -f "./Docs/HIG_COMPLIANCE_AUDIT.md"
echo 'Removing ./Docs/IOS_BUILD_ERROR_FIX.md'
rm -f "./Docs/IOS_BUILD_ERROR_FIX.md"
echo 'Removing ./Docs/IOS_FLOATING_BUTTONS_FIX.md'
rm -f "./Docs/IOS_FLOATING_BUTTONS_FIX.md"
echo 'Removing ./Docs/IOS_FLOATING_MENU_FIX.md'
rm -f "./Docs/IOS_FLOATING_MENU_FIX.md"
echo 'Removing ./Docs/IOS_PAGE_TRANSITIONS_AUDIT.md'
rm -f "./Docs/IOS_PAGE_TRANSITIONS_AUDIT.md"
echo 'Removing ./Docs/ISSUE_262_PHANTOM_DATE_FIX.md'
rm -f "./Docs/ISSUE_262_PHANTOM_DATE_FIX.md"
echo 'Removing ./Docs/Issues/ISSUE_401_PARITY_AUDIT.md'
rm -f "./Docs/Issues/ISSUE_401_PARITY_AUDIT.md"
echo 'Removing ./Docs/KEYBOARD_NAVIGATION_AUDIT.md'
rm -f "./Docs/KEYBOARD_NAVIGATION_AUDIT.md"
echo 'Removing ./Docs/LAYOUT_ERROR_STATE_AUDIT.md'
rm -f "./Docs/LAYOUT_ERROR_STATE_AUDIT.md"
echo 'Removing ./Docs/LOCALIZATION_KEYS_SHOWING_FIX.md'
rm -f "./Docs/LOCALIZATION_KEYS_SHOWING_FIX.md"
echo 'Removing ./Docs/MACOS_COMPILATION_FIXES.md'
rm -f "./Docs/MACOS_COMPILATION_FIXES.md"
echo 'Removing ./Docs/MAINACTOR_RECURSIVE_LOCK_ANALYSIS.md'
rm -f "./Docs/MAINACTOR_RECURSIVE_LOCK_ANALYSIS.md"
echo 'Removing ./Docs/NOTIFICATION_PERMISSION_LOG_SPAM_FIX.md'
rm -f "./Docs/NOTIFICATION_PERMISSION_LOG_SPAM_FIX.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_INDEX.md'
rm -f "./Docs/PLATFORM_UNIFICATION_INDEX.md"
echo 'Removing ./Docs/RECURRENCE_FIX_REPORT.md'
rm -f "./Docs/RECURRENCE_FIX_REPORT.md"
echo 'Removing ./Docs/RUNTIME_WARNINGS_FIXED.md'
rm -f "./Docs/RUNTIME_WARNINGS_FIXED.md"
echo 'Removing ./Docs/SWEEP_REPORT_DEC23.md'
rm -f "./Docs/SWEEP_REPORT_DEC23.md"
echo 'Removing ./Docs/THREADING_AUDIT.md'
rm -f "./Docs/THREADING_AUDIT.md"
echo 'Removing ./Docs/TIMER_PAGE_FREEZE_FIX.md'
rm -f "./Docs/TIMER_PAGE_FREEZE_FIX.md"
echo 'Removing ./Docs/TIMER_TAB_CRASH_FIX.md'
rm -f "./Docs/TIMER_TAB_CRASH_FIX.md"
echo 'Removing ./Docs/TOOLTIP_WRAPPING_FIX.md'
rm -f "./Docs/TOOLTIP_WRAPPING_FIX.md"
echo 'Removing ./Docs/UNIT_TEST_FAILURE_REPORT.md'
rm -f "./Docs/UNIT_TEST_FAILURE_REPORT.md"
echo 'Removing ./Docs/WATCH_CONNECTIVITY_FIX.md'
rm -f "./Docs/WATCH_CONNECTIVITY_FIX.md"
echo 'Removing ./Docs/WATCHOS_COMPANION_APP_FIX_OLD.md'
rm -f "./Docs/WATCHOS_COMPANION_APP_FIX_OLD.md"
echo 'Removing ./Docs/WATCHOS_COMPANION_AUDIT.md'
rm -f "./Docs/WATCHOS_COMPANION_AUDIT.md"
echo 'Removing ./Docs/WATCHOS_FIX_WKWATCHONLY.md'
rm -f "./Docs/WATCHOS_FIX_WKWATCHONLY.md"
echo 'Removing ./Docs/WATCHOS_INFOPLIST_FIX.md'
rm -f "./Docs/WATCHOS_INFOPLIST_FIX.md"
echo 'Removing ./Docs/WATCHOS_WKWATCHKITAPP_FIX.md'
rm -f "./Docs/WATCHOS_WKWATCHKITAPP_FIX.md"
echo 'Removing ./Docs/WINDOW_RESTORATION_FIX_TEST.md'
rm -f "./Docs/WINDOW_RESTORATION_FIX_TEST.md"
echo 'Removing ./MARKDOWN_AUDIT_REPORT_20260127_113125.md'
rm -f "./MARKDOWN_AUDIT_REPORT_20260127_113125.md"
echo 'Removing ./MARKDOWN_AUDIT_REPORT_20260127_113143.md'
rm -f "./MARKDOWN_AUDIT_REPORT_20260127_113143.md"
echo 'Removing ./Tests/Fixtures/TestGen/v1/INDEX.md'
rm -f "./Tests/Fixtures/TestGen/v1/INDEX.md"
echo 'Removing ./Tests/TEST_FAILURE_ANALYSIS.md'
rm -f "./Tests/TEST_FAILURE_ANALYSIS.md"
echo 'Removing ./TIMER_ENHANCEMENTS_INDEX.md'
rm -f "./TIMER_ENHANCEMENTS_INDEX.md"
echo 'Removing ./Docs/70_PERCENT_COVERAGE_PLAN.md'
rm -f "./Docs/70_PERCENT_COVERAGE_PLAN.md"
echo 'Removing ./Docs/ACCENT_COLOR_IMPLEMENTATION.md'
rm -f "./Docs/ACCENT_COLOR_IMPLEMENTATION.md"
echo 'Removing ./Docs/AI_ARCHITECTURE.md'
rm -f "./Docs/AI_ARCHITECTURE.md"
echo 'Removing ./Docs/ARCHITECTURE_CENTERING_FIX.md'
rm -f "./Docs/ARCHITECTURE_CENTERING_FIX.md"
echo 'Removing ./Docs/ARCHITECTURE_DIAGRAMS.md'
rm -f "./Docs/ARCHITECTURE_DIAGRAMS.md"
echo 'Removing ./Docs/AUTO_PLAN_IMPLEMENTATION.md'
rm -f "./Docs/AUTO_PLAN_IMPLEMENTATION.md"
echo 'Removing ./Docs/AUTO_RESCHEDULE_MISSED_EVENTS_PLAN.md'
rm -f "./Docs/AUTO_RESCHEDULE_MISSED_EVENTS_PLAN.md"
echo 'Removing ./Docs/BLUEPRINT_FIRST_ARCHITECTURE.md'
rm -f "./Docs/BLUEPRINT_FIRST_ARCHITECTURE.md"
echo 'Removing ./Docs/BUILD_FIXES_SETTINGS_IMPLEMENTATION.md'
rm -f "./Docs/BUILD_FIXES_SETTINGS_IMPLEMENTATION.md"
echo 'Removing ./Docs/CALENDAR_VIEWS_IMPLEMENTATION.md'
rm -f "./Docs/CALENDAR_VIEWS_IMPLEMENTATION.md"
echo 'Removing ./Docs/COMPREHENSIVE_TEST_PLAN.md'
rm -f "./Docs/COMPREHENSIVE_TEST_PLAN.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_IMPLEMENTATION_PLAN.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_IMPLEMENTATION_PLAN.md"
echo 'Removing ./Docs/COURSE_FILE_OPENING_IMPLEMENTATION.md'
rm -f "./Docs/COURSE_FILE_OPENING_IMPLEMENTATION.md"
echo 'Removing ./Docs/DETERMINISTIC_PLANNING_ENGINE.md'
rm -f "./Docs/DETERMINISTIC_PLANNING_ENGINE.md"
echo 'Removing ./Docs/ESTIMATION_PORTS_IMPLEMENTATION.md'
rm -f "./Docs/ESTIMATION_PORTS_IMPLEMENTATION.md"
echo 'Removing ./Docs/EVENTKIT_CONTRACT_TESTS_IMPLEMENTATION.md'
rm -f "./Docs/EVENTKIT_CONTRACT_TESTS_IMPLEMENTATION.md"
echo 'Removing ./Docs/FILE_CLASSIFICATION_IMPLEMENTATION.md'
rm -f "./Docs/FILE_CLASSIFICATION_IMPLEMENTATION.md"
echo 'Removing ./Docs/GLOBAL_LAYOUT_CONSISTENCY_IMPLEMENTATION.md'
rm -f "./Docs/GLOBAL_LAYOUT_CONSISTENCY_IMPLEMENTATION.md"
echo 'Removing ./Docs/HIG_IMPLEMENTATION_PLAN.md'
rm -f "./Docs/HIG_IMPLEMENTATION_PLAN.md"
echo 'Removing ./Docs/HYBRID_AI_ARCHITECTURE_IMPLEMENTATION.md'
rm -f "./Docs/HYBRID_AI_ARCHITECTURE_IMPLEMENTATION.md"
echo 'Removing ./Docs/ICLOUD_FILE_SYNC_IMPLEMENTATION.md'
rm -f "./Docs/ICLOUD_FILE_SYNC_IMPLEMENTATION.md"
echo 'Removing ./Docs/IOS_PRACTICE_TEST_ARCHITECTURE.md'
rm -f "./Docs/IOS_PRACTICE_TEST_ARCHITECTURE.md"
echo 'Removing ./Docs/IOS_PRACTICE_TEST_IMPLEMENTATION.md'
rm -f "./Docs/IOS_PRACTICE_TEST_IMPLEMENTATION.md"
echo 'Removing ./Docs/IOS_SETTINGS_IMPLEMENTATION.md'
rm -f "./Docs/IOS_SETTINGS_IMPLEMENTATION.md"
echo 'Removing ./Docs/ISSUE_103_BADGE_IMPLEMENTATION.md'
rm -f "./Docs/ISSUE_103_BADGE_IMPLEMENTATION.md"
echo 'Removing ./Docs/ISSUE_335_IMPLEMENTATION.md'
rm -f "./Docs/ISSUE_335_IMPLEMENTATION.md"
echo 'Removing ./Docs/ISSUE_336_IMPLEMENTATION.md'
rm -f "./Docs/ISSUE_336_IMPLEMENTATION.md"
echo 'Removing ./Docs/KEYBOARD_NAVIGATION_IMPLEMENTATION.md'
rm -f "./Docs/KEYBOARD_NAVIGATION_IMPLEMENTATION.md"
echo 'Removing ./Docs/LLM_ENFORCEMENT_ARCHITECTURE.md'
rm -f "./Docs/LLM_ENFORCEMENT_ARCHITECTURE.md"
echo 'Removing ./Docs/LOCALIZATION_ENFORCEMENT_PLAN.md'
rm -f "./Docs/LOCALIZATION_ENFORCEMENT_PLAN.md"
echo 'Removing ./Docs/LOCALIZATION_IMPLEMENTATION_PLAN.md'
rm -f "./Docs/LOCALIZATION_IMPLEMENTATION_PLAN.md"
echo 'Removing ./Docs/NATIVE_CLOCK_IMPLEMENTATION.md'
rm -f "./Docs/NATIVE_CLOCK_IMPLEMENTATION.md"
echo 'Removing ./Docs/PLANNER_LOCALIZATION_FIX.md'
rm -f "./Docs/PLANNER_LOCALIZATION_FIX.md"
echo 'Removing ./Docs/PLANNING_ENGINE_ENHANCEMENTS.md'
rm -f "./Docs/PLANNING_ENGINE_ENHANCEMENTS.md"
echo 'Removing ./Docs/PLATFORM_CAPABILITY_MATRIX_IMPLEMENTATION.md'
rm -f "./Docs/PLATFORM_CAPABILITY_MATRIX_IMPLEMENTATION.md"
echo 'Removing ./Docs/PRACTICE_TESTING_IMPLEMENTATION.md'
rm -f "./Docs/PRACTICE_TESTING_IMPLEMENTATION.md"
echo 'Removing ./Docs/PRACTICE_TESTING_V2_ROADMAP.md'
rm -f "./Docs/PRACTICE_TESTING_V2_ROADMAP.md"
echo 'Removing ./Docs/SCHEDULED_TESTS_IMPLEMENTATION.md'
rm -f "./Docs/SCHEDULED_TESTS_IMPLEMENTATION.md"
echo 'Removing ./Docs/TIMER_ARCHITECTURE_DIAGRAMS.md'
rm -f "./Docs/TIMER_ARCHITECTURE_DIAGRAMS.md"
echo 'Removing ./Docs/TIMER_ENHANCEMENTS_IMPLEMENTATION.md'
rm -f "./Docs/TIMER_ENHANCEMENTS_IMPLEMENTATION.md"
echo 'Removing ./Docs/TIMER_ENHANCEMENTS_ROLLOUT_PLAN.md'
rm -f "./Docs/TIMER_ENHANCEMENTS_ROLLOUT_PLAN.md"
echo 'Removing ./Docs/TIMER_IMPLEMENTATION_CHECKLIST.md'
rm -f "./Docs/TIMER_IMPLEMENTATION_CHECKLIST.md"
echo 'Removing ./Docs/TIMER_PAGE_RESTORATION_PLAN.md'
rm -f "./Docs/TIMER_PAGE_RESTORATION_PLAN.md"
echo 'Removing ./Docs/TIMER_PARITY_ALARMKIT_LIVEACTIVITY_PLAN.md'
rm -f "./Docs/TIMER_PARITY_ALARMKIT_LIVEACTIVITY_PLAN.md"
echo 'Removing ./Docs/WATCHOS_APP_IMPLEMENTATION.md'
rm -f "./Docs/WATCHOS_APP_IMPLEMENTATION.md"
echo 'Removing ./Docs/WATCHOS_COMPANION_IMPLEMENTATION.md'
rm -f "./Docs/WATCHOS_COMPANION_IMPLEMENTATION.md"
echo 'Removing ./Docs/WATCHOS_MERGE_IMPLEMENTATION_PLAN.md'
rm -f "./Docs/WATCHOS_MERGE_IMPLEMENTATION_PLAN.md"
echo 'Removing ./Docs/WATCHOS_SETTINGS_IMPLEMENTATION.md'
rm -f "./Docs/WATCHOS_SETTINGS_IMPLEMENTATION.md"
echo 'Removing ./Docs/WEEK_NAVIGATION_IMPLEMENTATION.md'
rm -f "./Docs/WEEK_NAVIGATION_IMPLEMENTATION.md"
echo 'Removing ./Tests/70_PERCENT_COVERAGE_PLAN.md'
rm -f "./Tests/70_PERCENT_COVERAGE_PLAN.md"
echo 'Removing ./Tests/ItoriUITests/EventEditRecurrence_IMPLEMENTATION_NOTES.md'
rm -f "./Tests/ItoriUITests/EventEditRecurrence_IMPLEMENTATION_NOTES.md"
echo 'Removing ./ai_review_prompts/review_ar_instructions.md'
rm -f "./ai_review_prompts/review_ar_instructions.md"
echo 'Removing ./ai_review_prompts/review_de_instructions.md'
rm -f "./ai_review_prompts/review_de_instructions.md"
echo 'Removing ./ai_review_prompts/review_es_instructions.md'
rm -f "./ai_review_prompts/review_es_instructions.md"
echo 'Removing ./ai_review_prompts/review_fr_instructions.md'
rm -f "./ai_review_prompts/review_fr_instructions.md"
echo 'Removing ./ai_review_prompts/review_ja_instructions.md'
rm -f "./ai_review_prompts/review_ja_instructions.md"
echo 'Removing ./ai_review_prompts/review_ru_instructions.md'
rm -f "./ai_review_prompts/review_ru_instructions.md"
echo 'Removing ./ai_review_prompts/review_zh-Hans_instructions.md'
rm -f "./ai_review_prompts/review_zh-Hans_instructions.md"
echo 'Removing ./Docs/ACCESSIBILITY_GUIDE.md'
rm -f "./Docs/ACCESSIBILITY_GUIDE.md"
echo 'Removing ./Docs/ACCESSIBILITY_TESTING_FRAMEWORK.md'
rm -f "./Docs/ACCESSIBILITY_TESTING_FRAMEWORK.md"
echo 'Removing ./Docs/ACCESSIBILITY_TESTING_QUICK_REFERENCE.md'
rm -f "./Docs/ACCESSIBILITY_TESTING_QUICK_REFERENCE.md"
echo 'Removing ./Docs/ADDING_COMPLETION_SOUNDS.md'
rm -f "./Docs/ADDING_COMPLETION_SOUNDS.md"
echo 'Removing ./Docs/ADVANCED_TESTING_STRATEGY.md'
rm -f "./Docs/ADVANCED_TESTING_STRATEGY.md"
echo 'Removing ./Docs/AI_ENGINE_PRODUCTION_READY.md'
rm -f "./Docs/AI_ENGINE_PRODUCTION_READY.md"
echo 'Removing ./Docs/AI_INTEGRATION_RULEBOOK.md'
rm -f "./Docs/AI_INTEGRATION_RULEBOOK.md"
echo 'Removing ./Docs/AI_USER_VISIBLE_BEHAVIOR_POLICY.md'
rm -f "./Docs/AI_USER_VISIBLE_BEHAVIOR_POLICY.md"
echo 'Removing ./Docs/ANIMATION_POLICY.md'
rm -f "./Docs/ANIMATION_POLICY.md"
echo 'Removing ./Docs/AnimationGuidelines.md'
rm -f "./Docs/AnimationGuidelines.md"
echo 'Removing ./Docs/Architecture/LLM_ENFORCEMENT_INVARIANT.md'
rm -f "./Docs/Architecture/LLM_ENFORCEMENT_INVARIANT.md"
echo 'Removing ./Docs/ASSIGNMENT_EDITOR_TEST_GUIDE.md'
rm -f "./Docs/ASSIGNMENT_EDITOR_TEST_GUIDE.md"
echo 'Removing ./Docs/AUTO_RESCHEDULE_HARDENING.md'
rm -f "./Docs/AUTO_RESCHEDULE_HARDENING.md"
echo 'Removing ./Docs/AUTO_RESCHEDULE_PRODUCTION_READY.md'
rm -f "./Docs/AUTO_RESCHEDULE_PRODUCTION_READY.md"
echo 'Removing ./Docs/AUTO_RESCHEDULE_QUICK_REFERENCE.md'
rm -f "./Docs/AUTO_RESCHEDULE_QUICK_REFERENCE.md"
echo 'Removing ./Docs/BACKGROUND_EXECUTION_SETUP.md'
rm -f "./Docs/BACKGROUND_EXECUTION_SETUP.md"
echo 'Removing ./Docs/CALENDAR_REVOKE_ACCESS_FEATURE.md'
rm -f "./Docs/CALENDAR_REVOKE_ACCESS_FEATURE.md"
echo 'Removing ./Docs/CALENDAR_SELECTION_FEATURE.md'
rm -f "./Docs/CALENDAR_SELECTION_FEATURE.md"
echo 'Removing ./Docs/Changelog_Roots.md'
rm -f "./Docs/Changelog_Roots.md"
echo 'Removing ./Docs/Changelog.md'
rm -f "./Docs/Changelog.md"
echo 'Removing ./Docs/CLEANING_PLACEHOLDER.md'
rm -f "./Docs/CLEANING_PLACEHOLDER.md"
echo 'Removing ./Docs/COMPREHENSIVE_ALGORITHM_TESTS.md'
rm -f "./Docs/COMPREHENSIVE_ALGORITHM_TESTS.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_CHECKLIST.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_CHECKLIST.md"
echo 'Removing ./Docs/CORE_DATA_CLOUDKIT_QUICK_REFERENCE.md'
rm -f "./Docs/CORE_DATA_CLOUDKIT_QUICK_REFERENCE.md"
echo 'Removing ./Docs/DASHBOARD_CLOCK_ENHANCEMENT.md'
rm -f "./Docs/DASHBOARD_CLOCK_ENHANCEMENT.md"
echo 'Removing ./Docs/DASHBOARD_HIG_QUICK_REFERENCE.md'
rm -f "./Docs/DASHBOARD_HIG_QUICK_REFERENCE.md"
echo 'Removing ./Docs/Developing/Changes/Changelog_Rules.md'
rm -f "./Docs/Developing/Changes/Changelog_Rules.md"
echo 'Removing ./Docs/Developing/Changes/Changelog.md'
rm -f "./Docs/Developing/Changes/Changelog.md"
echo 'Removing ./Docs/Developing/FolderRules.md'
rm -f "./Docs/Developing/FolderRules.md"
echo 'Removing ./Docs/Developing/Issues/Issues_Rules.md'
rm -f "./Docs/Developing/Issues/Issues_Rules.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_001.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_001.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_002.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_002.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_003.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_003.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_004.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_004.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_005.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_005.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_040.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_040.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_058.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_058.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_063.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_063.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_064.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_064.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_065.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_065.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Open/Ticket_066.md'
rm -f "./Docs/Developing/Issues/Tickets/Open/Ticket_066.md"
echo 'Removing ./Docs/Developing/Issues/Tickets/Ticket_Database.md'
rm -f "./Docs/Developing/Issues/Tickets/Ticket_Database.md"
echo 'Removing ./Docs/Developing/MigrationPlan_macOS.md'
rm -f "./Docs/Developing/MigrationPlan_macOS.md"
echo 'Removing ./Docs/Developing/ReleaseHygiene.md'
rm -f "./Docs/Developing/ReleaseHygiene.md"
echo 'Removing ./Docs/Developing/Roadmap.md'
rm -f "./Docs/Developing/Roadmap.md"
echo 'Removing ./Docs/Developing/Rules.md'
rm -f "./Docs/Developing/Rules.md"
echo 'Removing ./Docs/Developing/Style.md'
rm -f "./Docs/Developing/Style.md"
echo 'Removing ./Docs/Developing/TestsLayout.md'
rm -f "./Docs/Developing/TestsLayout.md"
echo 'Removing ./Docs/DIAGNOSTIC_INSTRUCTIONS.md'
rm -f "./Docs/DIAGNOSTIC_INSTRUCTIONS.md"
echo 'Removing ./Docs/DISPLAY_TITLE_FALLBACK_RULES.md'
rm -f "./Docs/DISPLAY_TITLE_FALLBACK_RULES.md"
echo 'Removing ./Docs/DOCUMENTATION_CONSISTENCY_CHECKLIST.md'
rm -f "./Docs/DOCUMENTATION_CONSISTENCY_CHECKLIST.md"
echo 'Removing ./Docs/DUPLICATE_HOMEWORK_REMOVED.md'
rm -f "./Docs/DUPLICATE_HOMEWORK_REMOVED.md"
echo 'Removing ./Docs/DUTCH_LOCALIZATION_ADDED.md'
rm -f "./Docs/DUTCH_LOCALIZATION_ADDED.md"
echo 'Removing ./Docs/DynamicTypeQAChecklist.md'
rm -f "./Docs/DynamicTypeQAChecklist.md"
echo 'Removing ./Docs/EDGE_CASE_TEST_COVERAGE.md'
rm -f "./Docs/EDGE_CASE_TEST_COVERAGE.md"
echo 'Removing ./Docs/ENERGY_UI_RELOCATION.md'
rm -f "./Docs/ENERGY_UI_RELOCATION.md"
echo 'Removing ./Docs/EVENT_DELETION_QUICK_REFERENCE.md'
rm -f "./Docs/EVENT_DELETION_QUICK_REFERENCE.md"
echo 'Removing ./Docs/FILE_CLASSIFICATION_QUICK_REFERENCE.md'
rm -f "./Docs/FILE_CLASSIFICATION_QUICK_REFERENCE.md"
echo 'Removing ./Docs/FINNISH_LOCALIZATION_GUIDE.md'
rm -f "./Docs/FINNISH_LOCALIZATION_GUIDE.md"
echo 'Removing ./Docs/GERMAN_LOCALIZATION_ADDED.md'
rm -f "./Docs/GERMAN_LOCALIZATION_ADDED.md"
echo 'Removing ./Docs/GLOBAL_LAYOUT_QUICK_REFERENCE.md'
rm -f "./Docs/GLOBAL_LAYOUT_QUICK_REFERENCE.md"
echo 'Removing ./Docs/HAPTICS_GUIDE.md'
rm -f "./Docs/HAPTICS_GUIDE.md"
echo 'Removing ./Docs/History/Completions/IOS_LOCALIZATION_COMPLETION.md'
rm -f "./Docs/History/Completions/IOS_LOCALIZATION_COMPLETION.md"
echo 'Removing ./Docs/History/Issues/ISSUE_177_B12_COMPLETION.md'
rm -f "./Docs/History/Issues/ISSUE_177_B12_COMPLETION.md"
echo 'Removing ./Docs/History/Issues/ISSUE_333_COMPLETION.md'
rm -f "./Docs/History/Issues/ISSUE_333_COMPLETION.md"
echo 'Removing ./Docs/History/Issues/ISSUE_390_COMPLETION.md'
rm -f "./Docs/History/Issues/ISSUE_390_COMPLETION.md"
echo 'Removing ./Docs/HOW_TO_GET_BUILD_BUTTON.md'
rm -f "./Docs/HOW_TO_GET_BUILD_BUTTON.md"
echo 'Removing ./Docs/HYBRID_AI_QUICK_REFERENCE.md'
rm -f "./Docs/HYBRID_AI_QUICK_REFERENCE.md"
echo 'Removing ./Docs/ICLOUD_FILE_MODULE_PERSISTENCE.md'
rm -f "./Docs/ICLOUD_FILE_MODULE_PERSISTENCE.md"
echo 'Removing ./Docs/ICLOUD_FILE_MODULE_QUICK_REFERENCE.md'
rm -f "./Docs/ICLOUD_FILE_MODULE_QUICK_REFERENCE.md"
echo 'Removing ./Docs/ICLOUD_SYNC_PRODUCTION_READY.md'
rm -f "./Docs/ICLOUD_SYNC_PRODUCTION_READY.md"
echo 'Removing ./Docs/ICLOUD_SYNC_SETUP.md'
rm -f "./Docs/ICLOUD_SYNC_SETUP.md"
echo 'Removing ./Docs/ICLOUD_SYNC_STRATEGY.md'
rm -f "./Docs/ICLOUD_SYNC_STRATEGY.md"
echo 'Removing ./Docs/ICLOUD_SYNC_TOGGLE_ADDED.md'
rm -f "./Docs/ICLOUD_SYNC_TOGGLE_ADDED.md"
echo 'Removing ./Docs/INFO_PLIST_QUICK_REF.md'
rm -f "./Docs/INFO_PLIST_QUICK_REF.md"
echo 'Removing ./Docs/INTEGRATION_CHECKLIST.md'
rm -f "./Docs/INTEGRATION_CHECKLIST.md"
echo 'Removing ./Docs/INTELLIGENT_SCHEDULING_SYSTEM.md'
rm -f "./Docs/INTELLIGENT_SCHEDULING_SYSTEM.md"
echo 'Removing ./Docs/IOS_APPEARANCE_PICKER_ADDED.md'
rm -f "./Docs/IOS_APPEARANCE_PICKER_ADDED.md"
echo 'Removing ./Docs/IOS_ASSIGNMENT_DETAIL_VIEW.md'
rm -f "./Docs/IOS_ASSIGNMENT_DETAIL_VIEW.md"
echo 'Removing ./Docs/IOS_BUILD_SUCCESS.md'
rm -f "./Docs/IOS_BUILD_SUCCESS.md"
echo 'Removing ./Docs/IOS_CRASH_DEBUG_GUIDE.md'
rm -f "./Docs/IOS_CRASH_DEBUG_GUIDE.md"
echo 'Removing ./Docs/IOS_DASHBOARD_CLEANUP.md'
rm -f "./Docs/IOS_DASHBOARD_CLEANUP.md"
echo 'Removing ./Docs/IOS_FLOATING_BUTTONS_BOTTOM_PLACEMENT.md'
rm -f "./Docs/IOS_FLOATING_BUTTONS_BOTTOM_PLACEMENT.md"
echo 'Removing ./Docs/IOS_FLOATING_MENU_QUICK_REFERENCE.md'
rm -f "./Docs/IOS_FLOATING_MENU_QUICK_REFERENCE.md"
echo 'Removing ./Docs/IOS_FLOATING_MENU_REDESIGN.md'
rm -f "./Docs/IOS_FLOATING_MENU_REDESIGN.md"
echo 'Removing ./Docs/IOS_LOCALIZATION_QUICK_REFERENCE.md'
rm -f "./Docs/IOS_LOCALIZATION_QUICK_REFERENCE.md"
echo 'Removing ./Docs/IOS_NATIVE_MENUS_MIGRATION.md'
rm -f "./Docs/IOS_NATIVE_MENUS_MIGRATION.md"
echo 'Removing ./Docs/IOS_NATIVE_MENUS_QUICK_REFERENCE.md'
rm -f "./Docs/IOS_NATIVE_MENUS_QUICK_REFERENCE.md"
echo 'Removing ./Docs/IOS_NAVIGATION_BUTTONS_LAYOUT.md'
rm -f "./Docs/IOS_NAVIGATION_BUTTONS_LAYOUT.md"
echo 'Removing ./Docs/IOS_PRACTICE_TAB_DEVICE_FILTERING.md'
rm -f "./Docs/IOS_PRACTICE_TAB_DEVICE_FILTERING.md"
echo 'Removing ./Docs/IOS_PRACTICE_TEST_QUICK_REFERENCE.md'
rm -f "./Docs/IOS_PRACTICE_TEST_QUICK_REFERENCE.md"
echo 'Removing ./Docs/IOS_SETTINGS_ORGANIZATION.md'
rm -f "./Docs/IOS_SETTINGS_ORGANIZATION.md"
echo 'Removing ./Docs/IOS_SETTINGS_QUICK_REFERENCE.md'
rm -f "./Docs/IOS_SETTINGS_QUICK_REFERENCE.md"
echo 'Removing ./Docs/IOS_TIME_ESTIMATION_LABELS.md'
rm -f "./Docs/IOS_TIME_ESTIMATION_LABELS.md"
echo 'Removing ./Docs/ISSUE_175H_LLM_OPTIONAL_LAYER.md'
rm -f "./Docs/ISSUE_175H_LLM_OPTIONAL_LAYER.md"
echo 'Removing ./Docs/ISSUE_262_QUICK_REFERENCE.md'
rm -f "./Docs/ISSUE_262_QUICK_REFERENCE.md"
echo 'Removing ./Docs/ISSUE_351_QUICK_REFERENCE.md'
rm -f "./Docs/ISSUE_351_QUICK_REFERENCE.md"
echo 'Removing ./Docs/ISSUE_388_CRITICAL_DISCOVERY.md'
rm -f "./Docs/ISSUE_388_CRITICAL_DISCOVERY.md"
echo 'Removing ./Docs/ISSUE_APPTASK_CODING_KEYS_PRIVATE.md'
rm -f "./Docs/ISSUE_APPTASK_CODING_KEYS_PRIVATE.md"
echo 'Removing ./Docs/ISSUE_APPTASK_INIT_CALL_SITES.md'
rm -f "./Docs/ISSUE_APPTASK_INIT_CALL_SITES.md"
echo 'Removing ./Docs/ISSUE_RECURRENCE_RULE_MISSING.md'
rm -f "./Docs/ISSUE_RECURRENCE_RULE_MISSING.md"
echo 'Removing ./Docs/ISSUE_RECURRENCE_TYPE_CONFUSION.md'
rm -f "./Docs/ISSUE_RECURRENCE_TYPE_CONFUSION.md"
echo 'Removing ./Docs/Issues.md'
rm -f "./Docs/Issues.md"
echo 'Removing ./Docs/Issues/BUILD-FAILURE-1.md'
rm -f "./Docs/Issues/BUILD-FAILURE-1.md"
echo 'Removing ./Docs/Issues/ISSUE_406_SYNC_FOUNDATION.md'
rm -f "./Docs/Issues/ISSUE_406_SYNC_FOUNDATION.md"
echo 'Removing ./Docs/KEYBOARD_SHORTCUTS.md'
rm -f "./Docs/KEYBOARD_SHORTCUTS.md"
echo 'Removing ./Docs/LAYOUT_CONSISTENCY_TESTS_CREATED.md'
rm -f "./Docs/LAYOUT_CONSISTENCY_TESTS_CREATED.md"
echo 'Removing ./Docs/LAYOUT_STRESS_RESULTS.md'
rm -f "./Docs/LAYOUT_STRESS_RESULTS.md"
echo 'Removing ./Docs/LICENSE.md'
rm -f "./Docs/LICENSE.md"
echo 'Removing ./Docs/LLM_ENFORCEMENT_QUICK_REFERENCE.md'
rm -f "./Docs/LLM_ENFORCEMENT_QUICK_REFERENCE.md"
echo 'Removing ./Docs/LLM_INTEGRATION.md'
rm -f "./Docs/LLM_INTEGRATION.md"
echo 'Removing ./Docs/LOCALIZATION_BUNDLE_ISSUE.md'
rm -f "./Docs/LOCALIZATION_BUNDLE_ISSUE.md"
echo 'Removing ./Docs/LOCALIZATION_DEVELOPER_GUIDE.md'
rm -f "./Docs/LOCALIZATION_DEVELOPER_GUIDE.md"
echo 'Removing ./Docs/LOCALIZATION_QUICK_REFERENCE_OLD.md'
rm -f "./Docs/LOCALIZATION_QUICK_REFERENCE_OLD.md"
echo 'Removing ./Docs/LOCALIZATION_WORKFLOW.md'
rm -f "./Docs/LOCALIZATION_WORKFLOW.md"
echo 'Removing ./Docs/LOCALIZATION_XCODE_SETUP.md'
rm -f "./Docs/LOCALIZATION_XCODE_SETUP.md"
echo 'Removing ./Docs/LOCATION_USAGE_REMOVED.md'
rm -f "./Docs/LOCATION_USAGE_REMOVED.md"
echo 'Removing ./Docs/MACOS_ACCENT_COLOR_REFACTOR.md'
rm -f "./Docs/MACOS_ACCENT_COLOR_REFACTOR.md"
echo 'Removing ./Docs/MACOS_CALENDAR_GRID_REFACTOR.md'
rm -f "./Docs/MACOS_CALENDAR_GRID_REFACTOR.md"
echo 'Removing ./Docs/MAIN_THREAD_DEBUGGER_ENHANCEMENTS.md'
rm -f "./Docs/MAIN_THREAD_DEBUGGER_ENHANCEMENTS.md"
echo 'Removing ./Docs/MANUAL_TESTING_CALENDAR_RECURRENCE.md'
rm -f "./Docs/MANUAL_TESTING_CALENDAR_RECURRENCE.md"
echo 'Removing ./Docs/MEETING_TIMES_SELECTOR_REDESIGN.md'
rm -f "./Docs/MEETING_TIMES_SELECTOR_REDESIGN.md"
echo 'Removing ./Docs/MULTI_PLATFORM_TEST_STRATEGY.md'
rm -f "./Docs/MULTI_PLATFORM_TEST_STRATEGY.md"
echo 'Removing ./Docs/MULTI_TARGET_ARCHITECTURE_GUIDE.md'
rm -f "./Docs/MULTI_TARGET_ARCHITECTURE_GUIDE.md"
echo 'Removing ./Docs/MULTI_TARGET_QUICK_REFERENCE.md'
rm -f "./Docs/MULTI_TARGET_QUICK_REFERENCE.md"
echo 'Removing ./Docs/NOTIFICATIONS_QUICK_REFERENCE.md'
rm -f "./Docs/NOTIFICATIONS_QUICK_REFERENCE.md"
echo 'Removing ./Docs/Other/CALENDAR_SCHEDULING.md'
rm -f "./Docs/Other/CALENDAR_SCHEDULING.md"
echo 'Removing ./Docs/Other/InterfacesAndLimitations.md'
rm -f "./Docs/Other/InterfacesAndLimitations.md"
echo 'Removing ./Docs/Other/ObjectivesAndEthics.md'
rm -f "./Docs/Other/ObjectivesAndEthics.md"
echo 'Removing ./Docs/Other/TASK_IMPORT_AND_SYNC.md'
rm -f "./Docs/Other/TASK_IMPORT_AND_SYNC.md"
echo 'Removing ./Docs/Planning'
rm -f "./Docs/Planning"
echo 'Removing Logic.md'
rm -f "Logic.md"
echo 'Removing ./Docs/PLATFORM_CAPABILITY_MATRIX_QUICK_REFERENCE.md'
rm -f "./Docs/PLATFORM_CAPABILITY_MATRIX_QUICK_REFERENCE.md"
echo 'Removing ./Docs/PLATFORM_CAPABILITY_MATRIX.md'
rm -f "./Docs/PLATFORM_CAPABILITY_MATRIX.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_FRAMEWORK.md'
rm -f "./Docs/PLATFORM_UNIFICATION_FRAMEWORK.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_IMPLEMENTATION_GUIDE.md'
rm -f "./Docs/PLATFORM_UNIFICATION_IMPLEMENTATION_GUIDE.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_QUICK_REFERENCE.md'
rm -f "./Docs/PLATFORM_UNIFICATION_QUICK_REFERENCE.md"
echo 'Removing ./Docs/PLATFORM_UNIFICATION_VISUAL_GUIDE.md'
rm -f "./Docs/PLATFORM_UNIFICATION_VISUAL_GUIDE.md"
echo 'Removing ./Docs/PRACTICE_TESTING_V1.md'
rm -f "./Docs/PRACTICE_TESTING_V1.md"
echo 'Removing ./Docs/PRODUCTION_PREP_SIGN_OFF.md'
rm -f "./Docs/PRODUCTION_PREP_SIGN_OFF.md"
echo 'Removing ./Docs/PRODUCTION_READINESS_EPIC_ISSUES.md'
rm -f "./Docs/PRODUCTION_READINESS_EPIC_ISSUES.md"
echo 'Removing ./Docs/PRODUCTION_RULES.md'
rm -f "./Docs/PRODUCTION_RULES.md"
echo 'Removing ./Docs/PRODUCTION_VERIFICATION_CHECKLIST_LLM.md'
rm -f "./Docs/PRODUCTION_VERIFICATION_CHECKLIST_LLM.md"
echo 'Removing ./Docs/QA-Calendar-AddEdit-Events.md'
rm -f "./Docs/QA-Calendar-AddEdit-Events.md"
echo 'Removing ./Docs/QUICK_ACTIONS_PLANNER_FILTERS_IMPLEMENTATION.md'
rm -f "./Docs/QUICK_ACTIONS_PLANNER_FILTERS_IMPLEMENTATION.md"
echo 'Removing ./Docs/QUICK_START_GUIDE.md'
rm -f "./Docs/QUICK_START_GUIDE.md"
echo 'Removing ./Docs/QUICK_TEST_REFERENCE.md'
rm -f "./Docs/QUICK_TEST_REFERENCE.md"
echo 'Removing ./Docs/README'
rm -f "./Docs/README"
echo 'Removing copy.md'
rm -f "copy.md"
echo 'Removing ./Docs/README.md'
rm -f "./Docs/README.md"
echo 'Removing ./Docs/RECURRENCE_STABILIZATION_DEC30.md'
rm -f "./Docs/RECURRENCE_STABILIZATION_DEC30.md"
echo 'Removing ./Docs/RELEASE_STRATEGY.md'
rm -f "./Docs/RELEASE_STRATEGY.md"
echo 'Removing ./Docs/RELEASE_v1.0.md'
rm -f "./Docs/RELEASE_v1.0.md"
echo 'Removing ./Docs/RESET_ALL_DATA_PRODUCTION.md'
rm -f "./Docs/RESET_ALL_DATA_PRODUCTION.md"
echo 'Removing ./Docs/Roots_README.md'
rm -f "./Docs/Roots_README.md"
echo 'Removing ./Docs/RUNTIME_WARNINGS_EXPLAINED.md'
rm -f "./Docs/RUNTIME_WARNINGS_EXPLAINED.md"
echo 'Removing ./Docs/SECURITY.md'
rm -f "./Docs/SECURITY.md"
echo 'Removing ./Docs/SMOOTH_SECONDS_HAND.md'
rm -f "./Docs/SMOOTH_SECONDS_HAND.md"
echo 'Removing ./Docs/STORAGE_DATA_INVENTORY.md'
rm -f "./Docs/STORAGE_DATA_INVENTORY.md"
echo 'Removing ./Docs/STUDY_HOURS_TIMER_INTEGRATION.md'
rm -f "./Docs/STUDY_HOURS_TIMER_INTEGRATION.md"
echo 'Removing ./Docs/SUBSCRIPTION_SETUP.md'
rm -f "./Docs/SUBSCRIPTION_SETUP.md"
echo 'Removing ./Docs/SYLLABUS_FILE_UPLOAD_ADDED.md'
rm -f "./Docs/SYLLABUS_FILE_UPLOAD_ADDED.md"
echo 'Removing ./Docs/TaskDependencies.md'
rm -f "./Docs/TaskDependencies.md"
echo 'Removing ./Docs/TESTFLIGHT_SETUP_GUIDE.md'
rm -f "./Docs/TESTFLIGHT_SETUP_GUIDE.md"
echo 'Removing ./Docs/TESTING_CHECKLIST.md'
rm -f "./Docs/TESTING_CHECKLIST.md"
echo 'Removing ./Docs/TESTING.md'
rm -f "./Docs/TESTING.md"
echo 'Removing ./Docs/TIMER_AUDIO_FEEDBACK_PLEASANT_TONES.md'
rm -f "./Docs/TIMER_AUDIO_FEEDBACK_PLEASANT_TONES.md"
echo 'Removing ./Docs/TIMER_ENHANCEMENTS_CHECKLIST.md'
rm -f "./Docs/TIMER_ENHANCEMENTS_CHECKLIST.md"
echo 'Removing ./Docs/TIMER_EPIC_QUICK_REFERENCE.md'
rm -f "./Docs/TIMER_EPIC_QUICK_REFERENCE.md"
echo 'Removing ./Docs/TIMER_FREEZE_ROOT_CAUSE_FOUND.md'
rm -f "./Docs/TIMER_FREEZE_ROOT_CAUSE_FOUND.md"
echo 'Removing ./Docs/TIMER_PAGE_MANUAL_TEST_CHECKLIST.md'
rm -f "./Docs/TIMER_PAGE_MANUAL_TEST_CHECKLIST.md"
echo 'Removing ./Docs/TIMER_REFACTOR_LESSONS_LEARNED.md'
rm -f "./Docs/TIMER_REFACTOR_LESSONS_LEARNED.md"
echo 'Removing ./Docs/UI_SNAPSHOT_TESTS.md'
rm -f "./Docs/UI_SNAPSHOT_TESTS.md"
echo 'Removing ./Docs/V1.1_PREPARATION_CHECKLIST.md'
rm -f "./Docs/V1.1_PREPARATION_CHECKLIST.md"
echo 'Removing ./Docs/WATCHOS_BUILD_ISSUE.md'
rm -f "./Docs/WATCHOS_BUILD_ISSUE.md"
echo 'Removing ./Docs/WATCHOS_BUILD_SUCCESS.md'
rm -f "./Docs/WATCHOS_BUILD_SUCCESS.md"
echo 'Removing ./Docs/WATCHOS_COMPANION_SETUP.md'
rm -f "./Docs/WATCHOS_COMPANION_SETUP.md"
echo 'Removing ./Docs/WATCHOS_DEVICE_BUILD_WORKAROUND.md'
rm -f "./Docs/WATCHOS_DEVICE_BUILD_WORKAROUND.md"
echo 'Removing ./Docs/WATCHOS_FREQUENT_SYNC.md'
rm -f "./Docs/WATCHOS_FREQUENT_SYNC.md"
echo 'Removing ./Docs/WATCHOS_QUICK_FIX.md'
rm -f "./Docs/WATCHOS_QUICK_FIX.md"
echo 'Removing ./Docs/WATCHOS_QUICK_START.md'
rm -f "./Docs/WATCHOS_QUICK_START.md"
echo 'Removing ./Docs/WEEK_NAVIGATION_QUICK_REFERENCE.md'
rm -f "./Docs/WEEK_NAVIGATION_QUICK_REFERENCE.md"
echo 'Removing ./Docs/WIKI_STRUCTURE.md'
rm -f "./Docs/WIKI_STRUCTURE.md"
echo 'Removing ./Docs/Wiki-Core-Concepts.md'
rm -f "./Docs/Wiki-Core-Concepts.md"
echo 'Removing ./Docs/Wiki-Data-and-Storage.md'
rm -f "./Docs/Wiki-Data-and-Storage.md"
echo 'Removing ./Docs/Wiki-Home.md'
rm -f "./Docs/Wiki-Home.md"
echo 'Removing ./Docs/Wiki-Planner-and-Scheduler.md'
rm -f "./Docs/Wiki-Planner-and-Scheduler.md"
echo 'Removing ./Docs/Wiki/Productivity/DragAndDrop.md'
rm -f "./Docs/Wiki/Productivity/DragAndDrop.md"
echo 'Removing ./Docs/Wiki/Productivity/Multitasking.md'
rm -f "./Docs/Wiki/Productivity/Multitasking.md"
echo 'Removing ./Docs/Wiki/Productivity/Multiwindow.md'
rm -f "./Docs/Wiki/Productivity/Multiwindow.md"
echo 'Removing ./Docs/Wiki/Productivity/Testing.md'
rm -f "./Docs/Wiki/Productivity/Testing.md"
echo 'Removing ./Docs/Wiki/Productivity/UTTypes.md'
rm -f "./Docs/Wiki/Productivity/UTTypes.md"
echo 'Removing ./Docs/XCODE_BUILD_BUTTON_TROUBLESHOOTING.md'
rm -f "./Docs/XCODE_BUILD_BUTTON_TROUBLESHOOTING.md"
echo 'Removing ./Docs/XCODE_PROJECT_SETTINGS.md'
rm -f "./Docs/XCODE_PROJECT_SETTINGS.md"
echo 'Removing ./ItoriTimerWidget/QUICK_SETUP.md'
rm -f "./ItoriTimerWidget/QUICK_SETUP.md"
echo 'Removing ./ItoriTimerWidget/SETUP_INSTRUCTIONS.md'
rm -f "./ItoriTimerWidget/SETUP_INSTRUCTIONS.md"
echo 'Removing ./Scripts/LOCALIZATION_QUICK_REFERENCE.md'
rm -f "./Scripts/LOCALIZATION_QUICK_REFERENCE.md"
echo 'Removing ./Scripts/LOCALIZATION_README.md'
rm -f "./Scripts/LOCALIZATION_README.md"
echo 'Removing ./Scripts/README.md'
rm -f "./Scripts/README.md"
echo 'Removing ./SharedCore/Resources/Sounds/CREDITS.md'
rm -f "./SharedCore/Resources/Sounds/CREDITS.md"
echo 'Removing ./SharedCore/Resources/Sounds/XCODE_SETUP_INSTRUCTIONS.md'
rm -f "./SharedCore/Resources/Sounds/XCODE_SETUP_INSTRUCTIONS.md"
echo 'Removing ./Tests/Fixtures/TestGen/v1/README.md'
rm -f "./Tests/Fixtures/TestGen/v1/README.md"
echo 'Removing ./Tests/ItoriUITests/UI_TESTS_DISABLED.md'
rm -f "./Tests/ItoriUITests/UI_TESTS_DISABLED.md"
echo 'Removing ./Tests/OptimizationTests/README.md'
rm -f "./Tests/OptimizationTests/README.md"
echo 'Removing ./Tests/READY_TO_RUN.md'
rm -f "./Tests/READY_TO_RUN.md"
echo 'Removing ./Tests/TestGen/README.md'
rm -f "./Tests/TestGen/README.md"
echo 'Removing ./Tests/TESTING_GUIDE.md'
rm -f "./Tests/TESTING_GUIDE.md"
echo 'Removing ./Tests/Unit/ItoriTests/Platform/TESTS_DISABLED.md'
rm -f "./Tests/Unit/ItoriTests/Platform/TESTS_DISABLED.md"
echo 'Removing ./Tests/Unit/ItoriTests/TestCoverageAudit.md'
rm -f "./Tests/Unit/ItoriTests/TestCoverageAudit.md"
echo 'Removing ./TIMER_ENHANCEMENTS_README.md'
rm -f "./TIMER_ENHANCEMENTS_README.md"
echo 'Removing ./website/README.md'
rm -f "./website/README.md"

echo 'Cleanup complete!'
echo 'Total files removed: 473'
