#!/bin/bash

echo "🔧 Creating new ItoriWatch target from scratch..."

# This script will recreate the watch target properly
echo "⚠️  This needs to be done in Xcode manually:"
echo ""
echo "1. DELETE the ItoriWatch target:"
echo "   - Select ItoriApp project → ItoriWatch target"
echo "   - Press Delete key"
echo "   - Confirm deletion"
echo ""
echo "2. CREATE new Watch App target:"
echo "   - File → New → Target"
echo "   - watchOS → Watch App"
echo "   - Product Name: ItoriWatch"
echo "   - Uncheck 'Include Notification Scene'"
echo "   - Click Finish"
echo ""
echo "3. ADD Swift files to new target:"
echo "   - Select all 7 .swift files in Platforms/watchOS"
echo "   - Show File Inspector (⌘⌥1)"
echo "   - Check 'ItoriWatch' in Target Membership"
echo ""
echo "4. DELETE the auto-created template files:"
echo "   - Delete ContentView.swift (template)"
echo "   - Delete ItoriWatchApp.swift (template, conflicts with ours)"
echo ""
echo "5. CONFIGURE Info.plist:"
echo "   - Already done, should copy over"
echo ""
echo "6. BUILD:"
echo "   - Clean (⌘⇧K)"
echo "   - Build (⌘B)"
echo ""
echo "✅ This will create a clean watch target without conflicts!"

